# Datos
aca lo que se buscara es poder concatenar la informacion de cada evento que se encuentra en los archivos json y tener las tablas de modo que estas puedan ser usadas para calculos futuros

In [1]:
from extract_data import *
import json
import pandas as pd

In [2]:
path="data\data\dataSD1500"

In [3]:
nombres=extract_file_name(path=path)
len(nombres)

26640

In [4]:
link=path+"/"+nombres[0]
data=open_file(path=link)
#extract_keys(file=data)

In [5]:
fdrec=concat_dict(key_name="fdrec",path=path)
fdrec

,id,gpsnanotime,hdSpectrumEye,hdCalibEye,hdXmaxEye,theta,dtheta,phi,dphi,l,...,altitude,cherenkovFraction,minViewAngle,uspL,duspL,uspR,duspR,hottestStationId,distSdpStation,distAxisStation
0,1,257161602,0,0,1,48.21,0.38,157.74,0.66,190.73,...,1389.45,0.08,63.34,229.80,9.60,0.26,0.05,310,54.05,711.71
1,4,278779315,0,0,1,46.34,0.45,255.79,0.68,300.22,...,1532.25,0.10,31.97,220.66,8.71,0.25,0.05,658,130.63,163.89
2,1,901642884,0,0,1,27.71,0.74,349.57,1.31,244.14,...,1384.84,0.08,47.52,233.85,8.93,0.25,0.04,246,31.26,608.84
3,1,814732146,0,0,1,45.88,0.40,118.58,0.53,177.78,...,1391.82,0.11,33.29,231.96,6.35,0.23,0.04,308,285.74,312.06
4,4,166608618,0,0,1,23.81,0.42,34.96,0.99,233.00,...,1548.61,0.11,44.82,232.43,10.05,0.26,0.05,643,599.18,599.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,3,446055306,1,0,1,34.69,0.43,233.58,0.67,266.18,...,1535.29,0.14,32.41,216.10,8.85,0.24,0.05,1506,256.84,376.97
3186,3,845250987,0,0,1,28.39,0.40,236.24,0.82,289.47,...,1388.48,0.10,46.71,239.40,8.79,0.24,0.05,1347,286.63,357.43
3187,3,913515575,0,0,1,46.31,0.91,277.47,0.93,293.41,...,1443.83,0.10,29.60,224.01,10.77,0.26,0.05,1486,317.17,392.21
3188,1,406001797,1,1,1,38.86,0.61,355.36,0.66,272.09,...,1387.24,0.10,43.29,236.70,7.97,0.24,0.05,224,489.57,815.57
3189,2,405994072,1,1,1,38.06,0.38,355.59,1.09,271.43,...,1387.23,0.07,101.55,234.16,8.41,0.26,0.05,224,532.39,709.06

In [6]:
sdrec=concat_dict(key_name="sdrec",path=path)
sdrec

,gpsnanotime,theta,dtheta,phi,dphi,energy,denergy,l,b,ra,...,chi2,ndf,geochi2,geondf,nbstat,recstations,n19,dn19,n68,dn68
0,226346000,18.89,0.96,33.54,1.01,4.179,0.265,210.91,-65.55,39.72,...,0.50,1.0,1.18,1.0,4,"[194, 195, 222, 198]",NaN,NaN,NaN,NaN
1,972896000,49.25,0.21,85.90,0.31,13.081,0.706,174.65,-30.84,56.82,...,4.39,5.0,4.84,4.0,8,"[215, 114, 213, 204, 216, 117, 116, 217]",NaN,NaN,NaN,NaN
2,638367000,12.44,0.97,106.58,3.55,4.514,0.434,25.88,-44.21,322.08,...,0.49,2.0,0.00,1.0,5,"[223, 113, 229, 111, 226]",NaN,NaN,NaN,NaN
3,238387000,54.83,0.27,335.25,0.31,4.590,0.450,250.82,-9.16,112.68,...,9.14,6.0,20.92,5.0,9,"[110, 117, 118, 109, 104, 116, 107, 101, 203]",NaN,NaN,NaN,NaN
4,902280000,38.05,0.38,320.20,0.77,3.763,0.448,346.11,-46.33,324.09,...,0.81,2.0,0.75,1.0,5,"[281, 291, 276, 280, 273]",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25081,999674000,76.50,0.10,18.40,0.10,7.479,0.887,196.30,-16.30,80.70,...,NaN,NaN,182.78,16.0,19,"[654, 382, 683, 381, 261, 681, 392, 675, 1018,...",1.4,0.2,1.4,0.2
25082,535542000,35.88,0.41,143.46,0.84,4.526,0.355,215.52,-18.80,87.08,...,0.71,1.0,0.49,1.0,4,"[295, 195, 316, 274]",NaN,NaN,NaN,NaN
25083,417531000,78.00,0.10,25.60,0.10,7.513,0.945,41.60,11.70,276.20,...,NaN,NaN,9.93,21.0,24,"[576, 508, 514, 458, 456, 571, 559, 578, 543, ...",1.4,0.2,1.4,0.2
25084,239178000,41.95,0.28,178.21,0.63,7.237,0.664,295.59,38.26,186.54,...,5.39,4.0,3.52,3.0,7,"[1465, 1502, 1401, 1409, 1410, 1513, 1408]",NaN,NaN,NaN,NaN
25085,438059000,68.30,0.30,145.50,0.30,4.477,0.589,28.20,37.10,247.30,...,NaN,NaN,4.95,5.0,8,"[544, 529, 574, 521, 547, 566, 575, 564]",0.8,0.1,0.8,0.1

In [7]:
path_2=path="data\data\dataSD750"

In [8]:
fdrec_path_2=concat_dict(key_name="fdrec",path=path_2)
fdrec_path_2

,id,gpsnanotime,hdSpectrumEye,hdCalibEye,hdXmaxEye,theta,dtheta,phi,dphi,l,...,altitude,cherenkovFraction,minViewAngle,uspL,duspL,uspR,duspR,hottestStationId,distSdpStation,distAxisStation
0,6,619754006,0,1,0,32.86,0.78,29.40,1.17,231.62,...,1548.59,0.13,34.93,220.91,10.50,0.25,0.05,643,285.64,311.10
1,6,486303582,0,1,0,25.18,0.31,76.46,1.60,249.18,...,1584.90,0.08,23.19,226.10,7.84,0.27,0.04,1574,203.08,330.76
2,6,217795418,0,1,0,2.50,0.70,300.89,18.72,244.42,...,1581.22,0.12,29.81,219.57,7.81,0.26,0.04,608,169.39,327.66
3,6,926661376,0,1,0,6.11,0.61,312.48,6.32,250.98,...,1581.22,0.13,28.83,221.98,9.75,0.25,0.05,608,285.75,285.88
4,6,851359519,0,1,0,26.71,0.30,195.60,0.62,245.45,...,1555.54,0.06,60.71,223.35,8.90,0.26,0.05,1774,165.03,168.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,6,701196666,0,1,0,28.24,0.37,143.88,0.67,193.35,...,1557.45,0.05,55.20,211.07,9.84,0.27,0.05,1825,9.15,39.79
193,6,735918260,0,1,0,19.42,1.11,40.73,2.83,236.75,...,1581.55,0.10,25.07,219.43,7.58,0.26,0.04,1827,316.98,369.34
194,6,736029926,0,1,0,22.75,0.49,50.37,1.80,210.73,...,1580.96,0.11,24.24,211.92,10.75,0.27,0.06,1625,218.02,218.09
195,6,512447340,0,1,0,19.87,0.17,261.26,2.30,262.54,...,1581.89,0.12,36.79,220.00,10.49,0.25,0.05,1829,143.38,166.04
196,6,165175405,0,1,0,31.56,0.53,27.17,0.89,251.35,...,1545.07,0.13,37.02,225.12,9.25,0.25,0.05,1840,122.87,179.87

In [9]:
sdrec_path_2=concat_dict(key_name="sdrec",path=path_2)
sdrec_path_2

,gpsnanotime,theta,phi,energy,l,b,ra,dec,x,dx,...,ds450,s35,beta,gamma,chi2,ndf,geochi2,nbstat,recstations,s38
0,650217435,28.51,0.42,0.198,-11.56,13.12,246.41,-30.26,-28939.4,30.18,...,1.82,14.89,-3.02,-0.30,9.81,8.0,4.31,8,"[1827, 608, 1829, 1625, 1790, 1830, 1627, 1832]",NaN
1,743559685,18.07,318.30,0.106,-8.57,-21.61,286.70,-45.74,-27780.3,34.20,...,1.39,7.97,-3.07,-0.31,6.26,0.0,0.00,3,"[1625, 710, 1574]",NaN
2,481967424,33.61,330.65,0.114,-3.93,-39.95,313.40,-44.59,-24523.0,60.71,...,1.26,8.60,-2.87,-0.32,5.52,2.0,1.01,4,"[1814, 819, 1810, 1774]",NaN
3,395818524,20.75,8.62,0.160,14.32,-35.23,309.87,-29.68,-23861.5,43.05,...,1.80,12.04,-3.09,-0.29,3.21,5.0,0.88,6,"[1772, 707, 1771, 1766, 1763, 1775]",NaN
4,981706229,2.79,241.90,0.136,0.10,-20.10,288.19,-37.58,-27402.0,50.56,...,2.56,10.22,-3.17,-0.30,6.03,5.0,4.18,6,"[1844, 1826, 639, 1811, 1841, 651]",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54476,873550508,39.87,211.14,0.112,-35.34,-70.00,2.48,-45.34,-25962.8,34.44,...,1.32,8.39,-2.75,-0.33,4.65,5.0,8.85,6,"[1769, 688, 1760, 1761, 1767, 698]",NaN
54477,696095836,14.80,333.08,0.126,-115.34,-39.38,72.87,-40.62,-25696.1,40.57,...,1.53,9.44,-3.10,-0.31,3.89,3.0,0.07,5,"[1769, 1765, 1767, 669, 1760]",NaN
54478,863992520,25.81,92.56,0.297,-153.58,-32.77,70.70,-9.32,-28472.2,11.38,...,2.08,22.28,-3.08,-0.28,11.17,7.0,2.28,7,"[701, 1625, 1627, 608, 1827, 1812, 710]",NaN
54479,287317785,22.04,73.54,0.136,-142.52,-22.39,84.52,-13.83,-26043.2,21.34,...,1.75,10.22,-2.98,-0.33,11.62,4.0,2.24,6,"[1764, 1773, 734, 1765, 1774, 1813]",NaN
54480,114038497,37.34,42.45,0.105,-136.10,5.67,112.98,-7.09,-27101.2,21.70,...,1.26,7.92,-2.79,-0.33,4.83,0.0,0.00,3,"[1773, 1622, 710]",NaN